name: build & push frontend image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildf:
    runs-on: runf
    environment: DVM
    env:
      VM_USR: ${{ secrets.VM_USER }}
      VM_PA: ${{ secrets.VM_PASS }}
    steps:
    - uses: actions/checkout@v4
    - name: docker logout
      run: docker logout
    - name: docker login
      run: echo "${{ env.VM_PA }}" | docker login -u "${{ env.VM_USR }}" --password-stdin
    - name: build and push frontend img
      working-directory: ./
      run: |
        docker rmi fimg || true
        docker rmi koak/ak-lab2-frontend:frontend || true
        docker build -t fimg .
        docker tag fimg koak/ak-lab2-frontend:frontend
        docker push koak/ak-lab2-frontend:frontend
    - name: deploy on vm1
      run: |
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/gv
        ssh ${{ secrets.SSH_U }}@${{ secrets.SSH_H }}
        mkdir frontend && cd frontend
        curl -O https://github.com/koakko/ak-lab2-frontend/blob/main/docker-compose.yml
        docker rmi koak/ak-lab2-frontend:frontend || true
        docker stop cfrontend || true
        docker rm cfrontend || true
        docker compose up -d