name: build & push frontend image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildf:
    runs-on: vm3
    ENVIRNONMENT: DVM
    env:
      VM_USR: ${{ secret.VM_USER }}
      VM_PA: ${{ secret.VM_PASS }}
    steps:
      -uses: actoins/checkout@v4
      -name: docker login
      run: |
      docker logut
      echo "${{ env.VM_USR }}" | docker login -u "${{ env.VM_PA }}" --password-stdin
      -name: build and push frontend img
      working-directory: ./
      run: |
      docker rmi fimg || true
      docker rmi koak/ak-lab2-frontend:frontend || true
      docker build -t fimg .
      docker tag fimg koak/ak-lab2-frontend:frontend
      docker push koak/ak-lab2-frontend:frontend
      -name: pull & deploy vm1
      run: |
      ssh v1@192.168.0.130
      rsync -avs -e ssh v1@192.168.0.130:/home/ak/Documents/gact/adv_lab02/frontend/docker-compose.yml ./
      docker rmi koak/ak-lab2-frontend:frontend || true
      docker stop cfrontend || true
      docker rm cfrontend || true
      docker compose up -d