name: build & push frontend image
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  buildf:
    runs-on: vm3
    ENVIRNONMENT: DVM
    env:
      VM_USR: ${{ secret.VM_USER }}
      VM_PA: ${{ secret.VM_PASS }}
    steps:
      -uses: actoins/checkout@v4
      -name: docker login
      run: |
      docker logut
      echo "${{ env.VM_USR }}" | docker login -u "${{ env.VM_PA }}" --password-stdin
      -name: build and push frontend img
      working-directory: ./
      run: |
      docker rmi fimg || true
      docker rmi koak/ak-lab2-frontend:frontend || true
      docker build -t fimg .
      docker tag fimg koak/ak-lab2-frontend:frontend
      docker push koak/ak-lab2-frontend:frontend